# Generated by Django 3.2.12 on 2024-03-02 09:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vehicles', '0001_initial'),
        ('my_silant', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='maintenance',
            name='car',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='my_silant_maintenance_set', to='vehicles.car', verbose_name='Машина'),
        ),
        migrations.AddField(
            model_name='maintenance',
            name='service_company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='my_silant.servicecompany', verbose_name='Организация, проводившая ТО'),
        ),
        migrations.AddField(
            model_name='maintenance',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_silant.typemaintenance', verbose_name='Вид ТО'),
        ),
        migrations.AddField(
            model_name='complaint',
            name='car',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='my_silant_complaint_set', to='vehicles.car', verbose_name='Машина'),
        ),
        migrations.AddField(
            model_name='complaint',
            name='method_recovery',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_silant.recoverymethod', verbose_name='Способ восстановления'),
        ),
        migrations.AddField(
            model_name='complaint',
            name='node_failure',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_silant.failure', verbose_name='Узел отказа'),
        ),
        migrations.AddField(
            model_name='complaint',
            name='service_company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='my_silant.servicecompany', verbose_name='Сервисная компания'),
        ),
    ]
